EMPTY_SET = set([])


SCRIBBLE_FILE_EXTENSION = 'scr'


KIND_MESSAGE_SIGNATURE = 'KIND_MESSAGE_SIGNATURE'
KIND_PAYLOAD_TYPE = 'KIND_PAYLOAD_TYPE'


# move these into the ast files?

MESSAGE_SIGNATURE_NODE_TYPE = 'MESSAGESIGNATURE'
PAYLOAD_NODE_TYPE = 'PAYLOAD'
PAYLOAD_ELEMENT_NODE_TYPE = 'PAYLOADELEMENT'

MODULE_NODE_TYPE = 'MODULE'
MODULE_DECL_NODE_TYPE = 'MODULEDECL'
#IMPORT_DECL_NODE_TYPE = 'IMPORTDECL'
IMPORT_MODULE_NODE_TYPE = 'IMPORTMODULE'
IMPORT_MEMBER_NODE_TYPE = 'IMPORTMEMBER'
PAYLOAD_DECL_NODE_TYPE = 'PAYLOADTYPEDECL'

ROLE_DECL_LIST_NODE_TYPE = 'ROLEDECLLIST'
ROLE_DECL_NODE_TYPE = 'ROLEDECL'
PARAMETER_DECL_LIST_NODE_TYPE = 'PARAMETERDECLLIST'
PARAMETER_DECL_NODE_TYPE = 'PARAMETERDECL'
ROLE_INSTANTIATION_LIST_NODE_TYPE = 'ROLEINSTANTIATIONLIST'
ROLE_INSTANTIATION_NODE_TYPE = 'ROLEINSTANTIATION'
ARGUMENT_LIST_NODE_TYPE = 'ARGUMENTLIST'
ARGUMENT_NODE_TYPE = 'ARGUMENT'

GLOBAL_PROTOCOL_DECL_NODE_TYPE = 'GLOBALPROTOCOLDECL'
GLOBAL_PROTOCOL_DEF_NODE_TYPE = 'GLOBALPROTOCOLDEF'
GLOBAL_PROTOCOL_BLOCK_NODE_TYPE = 'GLOBALPROTOCOLBLOCK'
GLOBAL_INTERACTION_SEQUENCE_NODE_TYPE = 'GLOBALINTERACTIONSEQUENCE'
GLOBAL_MESSAGE_TRANSFER_NODE_TYPE = 'GLOBALMESSAGETRANSFER'
GLOBAL_CHOICE_NODE_TYPE = 'GLOBALCHOICE'
GLOBAL_RECURSION_NODE_TYPE = 'GLOBALRECURSION'
GLOBAL_CONTINUE_NODE_TYPE = 'GLOBALCONTINUE'
GLOBAL_PARALLEL_NODE_TYPE = 'GLOBALPARALLEL'
GLOBAL_INTERRUPTIBLE_NODE_TYPE = 'GLOBALINTERRUPTIBLE'
GLOBAL_INTERRUPT_NODE_TYPE = 'GLOBALINTERRUPT'
GLOBAL_DO_NODE_TYPE = 'GLOBALDO'

# FIXME: local nodes are not ANTLR nodes
LOCAL_PROTOCOL_DECL_NODE_TYPE = 'LOCALPROTOCOLDECL'
LOCAL_PROTOCOL_DEF_NODE_TYPE = 'LOCALPROTOCOLDEF'
LOCAL_PROTOCOL_BLOCK_NODE_TYPE = 'LOCALPROTOCOLBLOCK'
LOCAL_INTERACTION_SEQUENCE_NODE_TYPE = 'LOCALINTERACTIONSEQUENCE'
#LOCAL_MESSAGE_TRANSFER_NODE_TYPE = 'LOCALMESSAGETRANSFER'
LOCAL_SEND_NODE_TYPE = 'LOCALSEND'
LOCAL_RECEIVE_NODE_TYPE = 'LOCALRECEIVE'
LOCAL_CHOICE_NODE_TYPE = 'LOCALCHOICE'
LOCAL_RECURSION_NODE_TYPE = 'LOCALRECURSION'
LOCAL_CONTINUE_NODE_TYPE = 'LOCALCONTINUE'
LOCAL_PARALLEL_NODE_TYPE = 'LOCALPARALLEL'
LOCAL_INTERRUPTIBLE_NODE_TYPE = 'LOCALINTERRUPTIBLE'
LOCAL_THROW_NODE_TYPE = 'LOCALTHROW'
LOCAL_CATCH_NODE_TYPE = 'LOCALCATCH'
LOCAL_DO_NODE_TYPE = 'LOCALDO'


# Duplicated from ScribbleNew.g; what's the best way to share it?
# Mostly used in projection (outputting local types)
MODULE_KW = 'module';
IMPORT_KW = 'import';
TYPE_KW = 'type';
PROTOCOL_KW = 'protocol';
GLOBAL_KW = 'global';
LOCAL_KW = 'local';
ROLE_KW = 'role';
SIG_KW = 'sig';
INSTANTIATES_KW = 'instantiates';

FROM_KW = 'from';
TO_KW = 'to';
CHOICE_KW = 'choice';
AT_KW = 'at';
OR_KW = 'or';
REC_KW = 'rec';
CONTINUE_KW = 'continue';
PAR_KW = 'par';
AND_KW = 'and';
INTERRUPTIBLE_KW = 'interruptible';
WITH_KW = 'with';
BY_KW = 'by';
DO_KW = 'do';
AS_KW = 'as';
SPAWN_KW = 'spawn';
THROWS_KW = 'throws';
CATCHES_KW = 'catches';

