#!/bin/sh

DIR=`dirname "$0"`/..
PARSERDIR=$DIR'/parser'

if [ ! -d "$PARSERDIR" ]; then
	mkdir $PARSERDIR
fi

#java -cp $DIR/antlr/antlr-3.1.3.jar org.antlr.Tool -o $PARSERDIR $DIR/src/scribble/Scribble.g
java -cp antlr/antlr-3.1.3.jar org.antlr.Tool -o parser src/scribble/Scribble.g
