#!/bin/sh

DIR=`dirname "$0"`/..
PARSERDIR=$DIR'/parser'

if [ ! -d "$PARSERDIR" ]; then
	mkdir $PARSERDIR
fi

java -cp $DIR/lib/antlr-3.1.3.jar org.antlr.Tool -o $PARSERDIR $DIR/src/scribble/Scribble.g
